module.exports = {
    name: 'qr',
    description: 'Generate QR codes from text',
    category: 'utility',
    permissions: ['user'],
    usage: '.qr <text>',
    aliases: ['qrcode', 'generateqr'],
    cooldown: 2000,

    async execute(ctx) {
        const { bot, message, args, sender, chatId, isGroup, reply } = ctx;

        try {
            if (args.length === 0) {
                return reply('❌ Please provide text to generate QR code.\n\nUsage: `.qr <text>`\n\nExample: `.qr https://example.com`');
            }

            const text = args.join(' ');
            
            if (text.length > 1000) {
                return reply('❌ Text is too long. Maximum 1000 characters allowed.');
            }

            await reply('🔄 Generating QR code...');

            // Generate QR code using qr-server.com API
            const qrUrl = `https://api.qrserver.com/v1/create-qr-code/?size=300x300&data=${encodeURIComponent(text)}`;
            
            // Send QR code as image
            await bot.sendMessage(chatId, {
                image: { url: qrUrl },
                caption: `📱 **QR CODE GENERATED**\n\n` +
                        `📝 **Text:** ${bot.utils.truncateText(text, 100)}\n` +
                        `👤 **Generated by:** @${sender.split('@')[0]}\n\n` +
                        `📖 Scan this QR code with any QR reader!`,
                mentions: [sender]
            });

            // Update user stats
            ctx.updateUserStats();

        } catch (error) {
            bot.logger.error('QR command failed:', error);
            return reply('❌ Failed to generate QR code. Please try again.');
        }
    }
};